# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            main:
              entity: { class: AppBundle:Users, property: cidentificator }


    firewalls:
        main:
          pattern: /.*
          form_login:
            check_path: /login
            login_path: /login
          logout: true
          security: true
          anonymous: true

